name: RNAquantification
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - _r-mutex=1.0.1=anacondar_1
  - binutils_impl_linux-64=2.36.1=h193b22a_2
  - binutils_linux-64=2.36=hf3e587d_10
  - bioconductor-annotate=1.72.0=r41hdfd78af_0
  - bioconductor-annotationdbi=1.56.1=r41hdfd78af_0
  - bioconductor-biobase=2.54.0=r41h5c21468_1
  - bioconductor-biocfilecache=2.2.0=r41hdfd78af_0
  - bioconductor-biocgenerics=0.40.0=r41hdfd78af_0
  - bioconductor-biocio=1.4.0=r41hdfd78af_0
  - bioconductor-biocparallel=1.28.3=r41h619a076_0
  - bioconductor-biomart=2.50.0=r41hdfd78af_0
  - bioconductor-biostrings=2.62.0=r41h5c21468_1
  - bioconductor-ctc=1.68.0=r41hdfd78af_0
  - bioconductor-delayedarray=0.20.0=r41h5c21468_1
  - bioconductor-deseq2=1.34.0=r41h619a076_1
  - bioconductor-dexseq=1.40.0=r41hdfd78af_0
  - bioconductor-edger=3.36.0=r41h619a076_1
  - bioconductor-genefilter=1.76.0=r41ha086028_1
  - bioconductor-genelendatabase=1.30.0=r41hdfd78af_1
  - bioconductor-geneplotter=1.72.0=r41hdfd78af_0
  - bioconductor-genomeinfodb=1.30.0=r41hdfd78af_0
  - bioconductor-genomeinfodbdata=1.2.7=r41hdfd78af_2
  - bioconductor-genomicalignments=1.30.0=r41h5c21468_1
  - bioconductor-genomicfeatures=1.46.1=r41hdfd78af_0
  - bioconductor-genomicranges=1.46.1=r41h5c21468_0
  - bioconductor-go.db=3.14.0=r41hdfd78af_1
  - bioconductor-goseq=1.46.0=r41hdfd78af_0
  - bioconductor-iranges=2.28.0=r41h5c21468_1
  - bioconductor-keggrest=1.34.0=r41hdfd78af_0
  - bioconductor-limma=3.50.1=r41h5c21468_0
  - bioconductor-matrixgenerics=1.6.0=r41hdfd78af_0
  - bioconductor-qvalue=2.26.0=r41hdfd78af_0
  - bioconductor-rhtslib=1.26.0=r41h5c21468_1
  - bioconductor-rsamtools=2.10.0=r41h619a076_1
  - bioconductor-rtracklayer=1.54.0=r41hdc01c10_3
  - bioconductor-s4vectors=0.32.3=r41h5c21468_0
  - bioconductor-summarizedexperiment=1.24.0=r41hdfd78af_0
  - bioconductor-xvector=0.34.0=r41h5c21468_1
  - bioconductor-zlibbioc=1.40.0=r41h5c21468_1
  - boost-cpp=1.74.0=h6cacc03_7
  - bowtie=1.3.1=py310h980a94c_2
  - bowtie2=2.4.5=py310he297e0b_3
  - bwidget=1.9.14=ha770c72_1
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.18.1=h7f98852_0
  - ca-certificates=2022.6.15=ha878542_0
  - cairo=1.16.0=ha12eb4b_1010
  - coreutils=8.25=1
  - curl=7.83.1=h7bff187_0
  - expat=2.4.8=h27087fc_0
  - fastp=0.23.2=hb7a2d85_2
  - fastqc=0.11.8=2
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=hab24e00_0
  - fontconfig=2.14.0=h8e229c2_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - freetype=2.12.1=hca18f0e_0
  - fribidi=1.0.10=h36c2ea0_0
  - gcc_impl_linux-64=10.4.0=h7ee1905_16
  - gcc_linux-64=10.4.0=h9215b83_10
  - gettext=0.19.8.1=h73d1719_1008
  - gfortran_impl_linux-64=10.4.0=h44b2e72_16
  - gfortran_linux-64=10.4.0=h69d5af5_10
  - gmp=6.2.1=h58526e2_0
  - graphite2=1.3.13=h58526e2_1001
  - gsl=2.7=he838d99_0
  - gxx_impl_linux-64=10.4.0=h7ee1905_16
  - gxx_linux-64=10.4.0=h6e491c6_10
  - harfbuzz=4.2.0=h40b6f09_0
  - hdf5=1.10.6=nompi_h6a2412b_1114
  - htslib=1.14=h9753748_2
  - icu=69.1=h9c3ff4c_0
  - isa-l=2.30.0=ha770c72_4
  - jpeg=9e=h166bdaf_2
  - kallisto=0.48.0=h0d531b0_1
  - kernel-headers_linux-64=2.6.32=he073ed8_15
  - keyutils=1.6.1=h166bdaf_0
  - kmer-jellyfish=2.3.0=h9f5acd7_3
  - krb5=1.19.3=h3790be6_0
  - ld_impl_linux-64=2.36.1=hea4e1c9_2
  - lerc=3.0=h9c3ff4c_0
  - libblas=3.9.0=16_linux64_openblas
  - libcblas=3.9.0=16_linux64_openblas
  - libcurl=7.83.1=h7bff187_0
  - libdeflate=1.10=h7f98852_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libffi=3.4.2=h7f98852_5
  - libgcc=7.2.0=h69d50b8_2
  - libgcc-devel_linux-64=10.4.0=h74af60c_16
  - libgcc-ng=12.1.0=h8d9b700_16
  - libgfortran-ng=12.1.0=h69a702a_16
  - libgfortran5=12.1.0=hdcd56e2_16
  - libglib=2.72.1=h2d90d5f_0
  - libgomp=12.1.0=h8d9b700_16
  - libiconv=1.16=h516909a_0
  - libjemalloc=5.2.1=h9c3ff4c_6
  - liblapack=3.9.0=16_linux64_openblas
  - libnghttp2=1.47.0=hdcd2b5c_1
  - libnsl=2.0.0=h7f98852_0
  - libopenblas=0.3.21=pthreads_h78a6416_2
  - libpng=1.6.37=h753d276_4
  - libsanitizer=10.4.0=hde28e3b_16
  - libsqlite=3.39.2=h753d276_1
  - libssh2=1.10.0=haa6b8db_3
  - libstdcxx-devel_linux-64=10.4.0=h74af60c_16
  - libstdcxx-ng=12.1.0=ha89aaad_16
  - libtiff=4.4.0=h0fcbabc_0
  - libuuid=2.32.1=h7f98852_1000
  - libwebp-base=1.2.4=h166bdaf_0
  - libxcb=1.13=h7f98852_1004
  - libxml2=2.9.12=h885dcf4_1
  - libzlib=1.2.12=h166bdaf_2
  - make=4.3=hd18ef5c_1
  - ncurses=6.3=h27087fc_1
  - numpy=1.23.2=py310h53a5b5f_0
  - openjdk=11.0.1=h516909a_1016
  - openssl=1.1.1q=h166bdaf_0
  - pandoc=2.19.2=ha770c72_0
  - pango=1.50.7=hbd2fdc8_0
  - pcre=8.45=h9c3ff4c_0
  - pcre2=10.37=hc3806b6_1
  - perl=5.32.1=2_h7f98852_perl5
  - pip=22.2.2=pyhd8ed1ab_0
  - pixman=0.40.0=h36c2ea0_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - python=3.10.6=h582c2e5_0_cpython
  - python_abi=3.10=2_cp310
  - r-amap=0.8_18=r41h5ee154c_2
  - r-ape=5.6_2=r41h43535f1_0
  - r-argparse=2.1.6=r41hc72bb7e_0
  - r-askpass=1.1=r41hcfec24a_2
  - r-assertthat=0.2.1=r41hc72bb7e_2
  - r-backports=1.4.1=r41hcfec24a_0
  - r-base=4.1.3=hd930d0e_0
  - r-base64enc=0.1_3=r41hcfec24a_1004
  - r-bh=1.78.0_0=r41hc72bb7e_0
  - r-biasedurn=1.07=r41h03ef668_1004
  - r-bit=4.0.4=r41hcfec24a_0
  - r-bit64=4.0.5=r41hcfec24a_0
  - r-bitops=1.0_7=r41h06615bd_0
  - r-blob=1.2.3=r41hc72bb7e_0
  - r-brio=1.1.3=r41hcfec24a_0
  - r-broom=1.0.1=r41hc72bb7e_0
  - r-bslib=0.4.0=r41hc72bb7e_0
  - r-cachem=1.0.6=r41hcfec24a_0
  - r-callr=3.7.2=r41hc72bb7e_0
  - r-catools=1.18.2=r41h7525677_0
  - r-cellranger=1.1.0=r41hc72bb7e_1004
  - r-cli=3.3.0=r41h7525677_0
  - r-clipr=0.8.0=r41hc72bb7e_0
  - r-cluster=2.1.3=r41h8da6f51_0
  - r-colorspace=2.0_3=r41h06615bd_0
  - r-cpp11=0.4.2=r41hc72bb7e_0
  - r-crayon=1.5.1=r41hc72bb7e_0
  - r-curl=4.3.2=r41hcfec24a_0
  - r-data.table=1.14.2=r41hcfec24a_0
  - r-dbi=1.1.3=r41hc72bb7e_0
  - r-dbplyr=2.2.1=r41hc72bb7e_0
  - r-desc=1.4.1=r41hc72bb7e_0
  - r-diffobj=0.3.5=r41hcfec24a_0
  - r-digest=0.6.29=r41h03ef668_0
  - r-dplyr=1.0.9=r41h7525677_0
  - r-dtplyr=1.2.2=r41hc72bb7e_0
  - r-ellipsis=0.3.2=r41hcfec24a_0
  - r-evaluate=0.16=r41hc72bb7e_0
  - r-fansi=1.0.3=r41h06615bd_0
  - r-farver=2.1.1=r41h7525677_0
  - r-fastcluster=1.2.3=r41h9c3ff4c_0
  - r-fastmap=1.1.0=r41h03ef668_0
  - r-fastmatch=1.1_3=r41hcfec24a_0
  - r-filelock=1.0.2=r41hcfec24a_1002
  - r-findpython=1.0.7=r41hc72bb7e_0
  - r-forcats=0.5.2=r41hc72bb7e_0
  - r-formatr=1.12=r41hc72bb7e_0
  - r-fs=1.5.2=r41h7525677_1
  - r-futile.logger=1.4.3=r41hc72bb7e_1003
  - r-futile.options=1.0.1=r41hc72bb7e_1002
  - r-gargle=1.2.0=r41hc72bb7e_0
  - r-generics=0.1.3=r41hc72bb7e_0
  - r-ggplot2=3.3.6=r41hc72bb7e_0
  - r-glue=1.6.2=r41h06615bd_0
  - r-googledrive=2.0.0=r41hc72bb7e_0
  - r-googlesheets4=1.0.1=r41h785f33e_0
  - r-gplots=3.1.3=r41hc72bb7e_0
  - r-gtable=0.3.1=r41hc72bb7e_0
  - r-gtools=3.9.3=r41h06615bd_0
  - r-haven=2.5.0=r41h7525677_0
  - r-highr=0.9=r41hc72bb7e_0
  - r-hms=1.1.2=r41hc72bb7e_0
  - r-htmltools=0.5.3=r41h7525677_0
  - r-httr=1.4.4=r41hc72bb7e_0
  - r-hwriter=1.3.2.1=r41hc72bb7e_0
  - r-ids=1.0.1=r41hc72bb7e_1
  - r-igraph=1.3.0=r41hf10d5bd_0
  - r-isoband=0.2.5=r41h03ef668_0
  - r-jquerylib=0.1.4=r41hc72bb7e_0
  - r-jsonlite=1.8.0=r41h06615bd_0
  - r-kernsmooth=2.23_20=r41h742201e_0
  - r-knitr=1.40=r41hc72bb7e_0
  - r-labeling=0.4.2=r41hc72bb7e_1
  - r-lambda.r=1.2.4=r41hc72bb7e_1
  - r-lattice=0.20_45=r41hcfec24a_0
  - r-lifecycle=1.0.1=r41hc72bb7e_0
  - r-locfit=1.5_9.6=r41h06615bd_0
  - r-lubridate=1.8.0=r41h03ef668_0
  - r-magrittr=2.0.3=r41h06615bd_0
  - r-mass=7.3_58.1=r41h06615bd_0
  - r-matrix=1.4_1=r41h0154571_0
  - r-matrixstats=0.62.0=r41h06615bd_0
  - r-memoise=2.0.1=r41hc72bb7e_0
  - r-mgcv=1.8_40=r41h0154571_0
  - r-mime=0.12=r41hcfec24a_0
  - r-modelr=0.1.9=r41hc72bb7e_0
  - r-munsell=0.5.0=r41hc72bb7e_1004
  - r-nlme=3.1_159=r41h8da6f51_0
  - r-openssl=2.0.2=r41hfaab4ff_0
  - r-phangorn=2.9.0=r41h37cf8d7_0
  - r-pillar=1.8.1=r41hc72bb7e_0
  - r-pkgconfig=2.0.3=r41hc72bb7e_1
  - r-pkgload=1.3.0=r41hc72bb7e_0
  - r-plogr=0.2.0=r41hc72bb7e_1003
  - r-plyr=1.8.7=r41h7525677_0
  - r-png=0.1_7=r41hcfec24a_1004
  - r-praise=1.0.0=r41hc72bb7e_1005
  - r-prettyunits=1.1.1=r41hc72bb7e_1
  - r-processx=3.7.0=r41h06615bd_0
  - r-progress=1.2.2=r41hc72bb7e_2
  - r-ps=1.7.1=r41h06615bd_0
  - r-purrr=0.3.4=r41hcfec24a_1
  - r-quadprog=1.5_8=r41h742201e_3
  - r-r6=2.5.1=r41hc72bb7e_0
  - r-rappdirs=0.3.3=r41hcfec24a_0
  - r-rcolorbrewer=1.1_3=r41h785f33e_0
  - r-rcpp=1.0.9=r41h7525677_1
  - r-rcpparmadillo=0.11.2.3.1=r41h9f5de39_0
  - r-rcurl=1.98_1.8=r41h06615bd_0
  - r-readr=2.1.2=r41h03ef668_0
  - r-readxl=1.4.1=r41hf23e330_0
  - r-rematch=1.0.1=r41hc72bb7e_1004
  - r-rematch2=2.1.2=r41hc72bb7e_1
  - r-reprex=2.0.2=r41hc72bb7e_0
  - r-reshape2=1.4.4=r41h03ef668_1
  - r-restfulr=0.0.15=r41h73dbb54_0
  - r-rjson=0.2.21=r41h7525677_1
  - r-rlang=1.0.5=r41h7525677_0
  - r-rmarkdown=2.16=r41hc72bb7e_0
  - r-rprojroot=2.0.3=r41hc72bb7e_0
  - r-rsqlite=2.2.8=r41h03ef668_0
  - r-rstudioapi=0.14=r41hc72bb7e_0
  - r-rvest=1.0.3=r41hc72bb7e_0
  - r-sass=0.4.2=r41h7525677_0
  - r-scales=1.2.1=r41hc72bb7e_0
  - r-selectr=0.4_2=r41hc72bb7e_1
  - r-sm=2.2_5.7.1=r41h8da6f51_0
  - r-snow=0.4_4=r41hc72bb7e_0
  - r-statmod=1.4.37=r41hc3ea6d6_0
  - r-stringi=1.7.6=r41h337692f_1
  - r-stringr=1.4.1=r41hc72bb7e_0
  - r-survival=3.4_0=r41h06615bd_0
  - r-sys=3.4=r41hcfec24a_0
  - r-testthat=3.1.4=r41h7525677_0
  - r-tibble=3.1.8=r41h06615bd_0
  - r-tidyr=1.2.0=r41h03ef668_0
  - r-tidyselect=1.1.2=r41hc72bb7e_0
  - r-tidyverse=1.3.2=r41hc72bb7e_0
  - r-tinytex=0.41=r41hc72bb7e_0
  - r-tzdb=0.3.0=r41h7525677_0
  - r-utf8=1.2.2=r41hcfec24a_0
  - r-uuid=1.1_0=r41h06615bd_0
  - r-vctrs=0.4.1=r41h7525677_0
  - r-vioplot=0.3.7=r41hc72bb7e_0
  - r-viridislite=0.4.1=r41hc72bb7e_0
  - r-vroom=1.5.7=r41h03ef668_0
  - r-waldo=0.4.0=r41hc72bb7e_0
  - r-withr=2.5.0=r41hc72bb7e_0
  - r-xfun=0.32=r41h7525677_0
  - r-xml=3.99_0.9=r41h06615bd_0
  - r-xml2=1.3.3=r41h03ef668_0
  - r-xtable=1.8_4=r41hc72bb7e_3
  - r-yaml=2.3.5=r41h06615bd_0
  - r-zoo=1.8_10=r41h06615bd_0
  - readline=8.1.2=h0f457ee_0
  - salmon=1.7.0=h10bb6b4_1
  - samtools=1.15=h3843a85_0
  - sed=4.8=he412f7d_0
  - setuptools=65.3.0=pyhd8ed1ab_1
  - sysroot_linux-64=2.12=he073ed8_15
  - tbb=2020.2=h4bd325d_4
  - tk=8.6.12=h27826a3_0
  - tktable=2.10=hb7b940f_3
  - trimmomatic=0.39=hdfd78af_2
  - trinity=2.13.2=h15cb65e_2
  - tzdata=2022c=h191b570_0
  - wheel=0.37.1=pyhd8ed1ab_0
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.0.10=h7f98852_0
  - xorg-libsm=1.2.3=hd9c2040_1000
  - xorg-libx11=1.7.2=h7f98852_0
  - xorg-libxau=1.0.9=h7f98852_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h7f98852_1
  - xorg-libxrender=0.9.10=h7f98852_1003
  - xorg-libxt=1.2.1=h7f98852_2
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h7f98852_1002
  - xorg-xproto=7.0.31=h7f98852_1007
  - xz=5.2.6=h166bdaf_0
  - zlib=1.2.12=h166bdaf_2
  - zstd=1.5.2=h6239696_4
